[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/looplab/fsm"

[[constraint]]
  name = "github.com/stianeikeland/go-rpio"
  version = "4.0.0"
